# Generated by Django 5.0.7 on 2024-07-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preacher',
            name='stream_link_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
