# Generated by Django 5.0.7 on 2024-07-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preachers', '0002_alter_preacher_stream_link_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='preacher',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
